### ISSUE TITLE
[Enhancement] Request for adaptation immersive-translate

### ISSUE THREAD

**Issue by zer0yu** [akl7777777/bob-plugin-akl-deepl-free-translate#1]
Your bob deepl plugin is great!
I would like to ask if it can be adapted to the chrome plugin [immersive-translate](https://github.com/immersive-translate/immersive-translate) ?

**Comment by akl7777777** [comment]
Oh, I know about "immersive translation", I've been using it recently. But I'm not sure if I understand "adapt" correctly. Do you mean that I should modify the code so that it works in immersive translation? Or do you want to use my code in immersive translation?

**Comment by akl7777777** [comment]
Thank you for your interest in my bob deepl plugin! At the moment, I have not created a version of the plugin that is compatible with immersive-translate. However, if you are interested in using my plugin with immersive-translate, I would be happy to explore the possibility of modifying the code to make it compatible. Please let me know if this is something you would like to pursue further. And my bob deepl plugin is open source, and you are free to use the code.

**Comment by zer0yu** [comment]
I'm sorry if I didn't make my point clearly. Can you modify your code to make it work on the immersive-translation?

**Comment by akl7777777** [comment]
Thank you for clarifying your question. I understand that you would like me to modify my bob deepl plugin code to work with the immersive-translate plugin. I am happy to explore the possibility of making my plugin compatible with immersive-translate. However, I would need to look into the technical details of the immersive-translate plugin to understand what changes would be necessary. Can you provide me with more information on the immersive-translate plugin and how it works? This will help me to better understand the changes that may be required.

**Comment by zer0yu** [comment]
Maybe this link below will be of some help, thanks

https://immersive-translate.owenyoung.com/CONTRIBUTION

**Comment by akl7777777** [comment]
Thank you for your message. I have joined the team , so you can expect to see the compatibility feature in future versions of the plugin. Thank you again for your interest in this project!
