### ISSUE TITLE
大佬可以做一个CNKI学术翻译的bob插件吗？

### ISSUE THREAD

**Issue by ZacharyLauGitHub** [akl7777777/bob-plugin-akl-deepl-free-translate#2]
https://dict.cnki.net/index
https://github.com/windingwind/zotero-pdf-translate

**Comment by akl7777777** [comment]
@ZacharyLauGitHub 刚看了一下,网站加密是用的标准库,不算简单也不算太难,然后顺手撸了一版,,着急你就先凑合用,有些功能还不完善,后期慢慢优化吧==>[CNKI学术翻译Bob插件](https://github.com/akl7777777/bob-plugin-akl-cnki-free-translate)

**Comment by ZacharyLauGitHub** [comment]
@akl7777777 大佬的速度太快了吧，我用了一下挺好的，非常感谢！
