### ISSUE TITLE
貌似不可用了，是不是官网算法更新了

### ISSUE THREAD

**Issue by linzhou111** [akl7777777/bob-plugin-akl-deepl-free-translate#4]
cause: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20)
      at TLSWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }

**Comment by akl7777777** [comment]
@linzhou111 感谢反馈,不过我这边尝试了一下,是可以的,要不你试着在正式版和beta之间切换下,如下图,那个报错信息看起来是网络问题,也可以换个网络环境试试,比如把提子关一下
<img width="726" alt="image" src="https://user-images.githubusercontent.com/84266551/227063991-63b14c7f-8441-476c-8b56-acb1d7487b43.png">
