### ISSUE TITLE
提示：请求过多

### ISSUE THREAD

**Issue by LIZSK** [akl7777777/bob-plugin-akl-deepl-free-translate#5]
你好，翻译3-4次就会出现
{"jsonrpc":"2.0","error":{"message":"Too many requests","code":1042912}}

**Comment by akl7777777** [comment]
你好,请切换一下这里的版本再试,如图,尽量用正式版
<img width="727" alt="image" src="https://user-images.githubusercontent.com/84266551/229360866-98b438f1-463c-401f-86dc-2d5fa5f22938.png">

**Comment by LIZSK** [comment]
感谢你的回复。我使用的是正式版本，但还是显示错误

From: akl7777777 ***@***.***>
Date: Sunday, 2 April 2023 at 15:56
To: akl7777777/bob-plugin-akl-deepl-free-translate ***@***.***>
Cc: LIZSK ***@***.***>, Author ***@***.***>
Subject: Re: [akl7777777/bob-plugin-akl-deepl-free-translate] 提示：请求过多 (Issue #5)

你好,请切换一下这里的版本再试,如图,尽量用正式版
[image]<https://user-images.githubusercontent.com/84266551/229360866-98b438f1-463c-401f-86dc-2d5fa5f22938.png>

―

**Comment by akl7777777** [comment]
出现这个问题之前,是否翻译过大段内容呢?  或者能否切换Alpha或者beta试试
