### ISSUE TITLE
用着用着就 Too many requests

### ISSUE THREAD

**Issue by pfzhan** [akl7777777/bob-plugin-akl-deepl-free-translate#7]
<img width="392" alt="image" src="https://user-images.githubusercontent.com/13960353/235668793-97bf47dc-5474-49ec-a3ca-5190ae1cca19.png">

**Comment by akl7777777** [comment]
原因:
2种可能:1.你当前使用的代理服务IP已经有很多人在使用DeepL官网的免费翻译,从而导致超过了官网后台限制的最大频率;2.你当前使用的IP或者是同一个局域网下其他成员短时间内使用量过大;

解决方法:
在插件设置中,切换Alpha或者Beta即可继续使用,不过建议在后台解除限制后还是切回自己的IP;
